In [1]:
import pandas as pd
import numpy as np

#https://github.com/EagleAdelaide/FinSen_Dataset
df = pd.read_csv("https://raw.githubusercontent.com/EagleAdelaide/FinSen_Dataset/refs/heads/main/data.pptx/FinSen_US_Categorized_Timestamp.csv")
df.head(10)

,Title,Tag,Time,Content
0,"TSX Slightly Down, Books Weekly Gains",Stock Market,16/07/2023,"TSX Slightly Down, Books Weekly GainsUnited St..."
1,UnitedHealth Hits 4-week High,stocks,15/07/2023,UnitedHealth Hits 4-week HighUnited States sto...
2,Cisco Systems Hits 4-week Low,stocks,15/07/2023,Cisco Systems Hits 4-week LowUnited States sto...
3,AT&T Hits All-time Low,stocks,15/07/2023,AT&T Hits All-time LowUnited States stocksAT&T...
4,Microsoft Hits 4-week High,stocks,15/07/2023,Microsoft Hits 4-week HighUnited States stocks...
5,JPMorgan Hits 16-month High,stocks,15/07/2023,JPMorgan Hits 16-month HighUnited States stock...
6,US Export Prices Fall More than Expected,Export Prices MoM,15/07/2023,US Export Prices Fall More than ExpectedUnited...
7,Citigroup earnings above expectations at 1.37 USD,Earnings,15/07/2023,Citigroup earnings above expectations at 1.37 ...
8,US Treasury Yields Below Recent Highs,Government Bond 10Y,15/07/2023,US Treasury Yields Below Recent Highs United S...
9,Wells Fargo earnings above expectations at 1.2...,Earnings,15/07/2023,Wells Fargo earnings above expectations at 1.2...

In [2]:
nasdaq_hist_data = pd.read_csv("./data/HistoricalData_1750671813123.csv")

#nasdaq_hist_data.describe(include=[np.number])

nasdaq_hist_data['change'] = np.round(
            (nasdaq_hist_data['Open'] - nasdaq_hist_data['Close/Last']) / nasdaq_hist_data['Open'], 5
        )

# based on Market-Wide Circuit Breakers of the New Yorck Stock Exchange
# https://www.nyse.com/markets/nyse/trading-info
# 1 - Strong gain (>= +20%)
# 2 - Significant gain (+13% to <20%)
# 3 - Moderate gain (+7% to <13%)
# 4 - Stable movement (-7% to <+7%)
# 5 - Moderate loss (-13% to <-7%)
# 6 - Significant loss (-20% to <-13%)
# 7 - Strong loss (< -20%)
conditions = [
    (nasdaq_hist_data['change'] >= 0.20),
    ((nasdaq_hist_data['change'] >= 0.13) & (nasdaq_hist_data['change'] < 0.20)),
    ((nasdaq_hist_data['change'] >= 0.07) & (nasdaq_hist_data['change'] < 0.13)),
    ((nasdaq_hist_data['change'] >= -0.07) & (nasdaq_hist_data['change'] < 0.07)),
    ((nasdaq_hist_data['change'] >= -0.13) & (nasdaq_hist_data['change'] < -0.07)),
    ((nasdaq_hist_data['change'] >= -0.20) & (nasdaq_hist_data['change'] < -0.13)),
    (nasdaq_hist_data['change'] < -0.20)
]

choices = [1, 2, 3, 4, 5, 6, 7]

nasdaq_hist_data['change_status'] = np.select(conditions, choices, default=np.nan)    
nasdaq_hist_data['change'] = nasdaq_hist_data['change'].apply('{:.2f}%'.format)
nasdaq_hist_data.head(10)

         Date  Close/Last      Open      High       Low  change  change_status
0  06/20/2025    19447.41  19639.41  19696.11  19380.58   0.01%            4.0
1  06/18/2025    19546.27  19526.92  19660.77  19489.56  -0.00%            4.0
2  06/17/2025    19521.09  19627.08  19666.56  19485.44   0.01%            4.0
3  06/16/2025    19701.21  19550.75  19733.31  19550.75  -0.01%            4.0
4  06/13/2025    19406.83  19450.92  19591.87  19367.42   0.00%            4.0
5  06/12/2025    19662.48  19578.87  19690.61  19553.56  -0.00%            4.0
6  06/11/2025    19615.88  19779.35  19800.46  19551.34   0.01%            4.0
7  06/10/2025    19714.99  19620.11  19730.38  19539.09  -0.00%            4.0
8  06/09/2025    19591.24  19573.14  19637.56  19531.10  -0.00%            4.0
9  06/06/2025    19529.95  19526.99  19593.18  19464.84  -0.00%            4.0